FROM node:16-alpine
WORKDIR /app
COPY ./package.json .
RUN npm install
RUN mkdir -p /app/node_modules/.cache && chmod -R 777 /app/node_modules/.cache
RUN echo "fs.inotify.max_user_watches=524288" >> /etc/sysctl.conf
# RUN chown -R node:node /app/node_modules
# USER node
COPY . .
CMD ["npm", "run", "start"]